### PR TITLE
Improve makefile

### PR DESCRIPTION
**Pull request by Hugome**
- Generic rules
 - Variables for compilations
 - make clean without EXECHAX, FWVER
 - Auto compilation of oot3d_savetool

### CODE REVIEW

**Comment by yellows8** [comment]
Those "requiments" typos need fixed too.

**Comment by Hugome** [comment]
Fixed

**Comment by yellows8** [comment]
Can you squash those commits as well?

**Comment by Hugome** [comment]
It's done.

**Pull request merged**
